config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'users/json' => 'users#list_json'
  root 'static_pages#home'
  get 'signup' => 'users#new'
  get 'creategroup' => 'groups#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout'                 => 'sessions#destroy'
  get 'friends/add/:id'          => 'friends#add'
  post 'friends/remove/:id'       => 'friends#remove'
  get 'users/friends/add/:id'    => 'friends#add'
  post 'users/friends/remove/:id' => 'friends#remove'
  get 'friends' => 'friends#index'
  get 'groups/:id' => 'groups#show'
  delete 'groups/remove/:id' => 'groups#destroy'
  post 'users/destroy/:id' => 'users#destroy'
  get 'groups/changestatus/:id' => 'groups#changestatus'
  get 'microposts/destroy/:id' => 'microposts#destroy'
  post 'microposts/post' => 'microposts#post'
  delete 'groups/microposts/destroy/:id' => 'microposts#destroy'
  get 'groups/microposts/edit/:id' => 'microposts#edit'
  get 'microposts/edit/:id' => 'microposts#edit'
  get 'msg/list' => 'text_chat#list', as: :messages
  get 'users/msg/new/:id' => 'text_chat#new', as: :compose
  post 'msg/send' => 'text_chat#send_msg'
  get 'users/video/:id' => 'video_chat#start'
  get 'msg/dialog/:id' => 'text_chat#dialog', as: :dialog
  match 'users/video/auth' => 'video_chat#auth', via: [:get, :post], as: :video
  resources :users
  resources :friends
  resources :groups
  resources :microposts, only: [:create]
end

app/models/friend.rb
class Friend < ActiveRecord::Base
  belongs_to :user
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :microposts, dependent: :destroy
  has_many :users

  def feed
    Micropost.where("group_id = ?", id)
  end

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
end

app/models/user.rb
class User < ActiveRecord::Base
  def feed
    Micropost.where("user_id = ?", id)
  end
  belongs_to :group
  has_many :microposts, dependent: :destroy
  has_many :friends, dependent: :destroy
  has_many :messages, dependent: :destroy
  validates :login, presence: true, length: {maximum: 50},
            uniqueness: {case_sensitive: false}
  has_secure_password

  validates :password, length: {minimum: 5}
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def show
    @group = Group.find(params[:id])
    @micropost = @group.microposts.build
    @feed_items = @group.feed.paginate(page: params[:page])
    @microposts = @group.microposts.paginate(page: params[:page])
  end
  def changestatus
    @group = Group.find(params[:id])
    if @group.status == true
      @group.status = false
    else
      @group.status = true
    end
    @group.save
    redirect_to @group
  end
  def destroy
    @group = Group.find(params[:id])
    Micropost.destroy_all(group_id:@group.id)
    Group.delete(@group)

    flash[:success] = "Group has been deleted"
    redirect_to groups_path
  end
  def new
    @group = Group.new
  end
  def index
    @groups = Group.all
  end
  def create
    params.permit!
    puts params
    @group = Group.new(status:params[:group][:status], name:params[:group][:name],owner_id:current_user.id)
    if @group.save
      puts @group
      flash[:success] = "Your group has been created"
      redirect_to groups_path
    else
      render 'new'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  #Returns the full title on a per-page basis
  def full_title(page_title = '')
    base_title = "Social network"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
  def getstatus(group)
    if group.status == true
      'open'
    else
      'closed'
    end
  end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def admin?
    @current_user.admin
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  def current_user?(user)
    user == current_user
  end
end

app/helpers/text_chat_helper.rb
module TextChatHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/index.html.erb
<% provide(:title, 'All groups') %>
<h1>All groups</h1>
<ul class="groups">

  <% if !Array(@groups).empty? %>
  <table class="table">
    <thead>
    <tr>
      <th>Name of group</th>
      <th></th>
    </tr>
    </thead>
    <tbody>

    <% Array(@groups).each do |group| %>
        <% if getstatus(group) !='closed' || group.owner_id == current_user.id || current_user.admin? %>
        <tr>
          <td>
            <%= link_to "#{group.name}", group %>
          </td>

          <% if current_user.admin? || current_user.id == group.owner_id %>
              <td>
                <%= link_to "Remove group", "groups/remove/#{group.id}", method: :delete, class: "btn btn-primary", data: {confirm: "You sure?"} %>
              </td>
          <% end %>
        </tr>
        <%end%>


    <% end %>

    <tbody>
    </table>
      <% else %>
  <h2>There are no groups yet!!! Yours will be first</h2>
  <% end %>
  <%= link_to 'Create group', creategroup_path, class: "btn btn-lg btn-primary"%>
</ul>

app/views/groups/new.html.erb
<% provide(:title, 'Create group') %>
<h1>Create group</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@group) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
        <%= f.label :status %>
        <%= f.select :status, [['Open', 1], ['Closed', 0]] %>
        <%= f.submit "Create my group", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/groups/show.html.erb
<h1><%= @group.name %></h1>
<div>
  <% if @group.owner_id == current_user.id || current_user.admin? %>
    <%= link_to "Change status (status #{getstatus(@group)})", "changestatus/#{@group.id}", class: "btn btn-lg btn-primary"%>
  <% end %>
</div>
<div class="row">
  <aside class="col-md-4">
    <!--<section class="user_info">-->
      <!--<%= render 'shared/user_info' %>-->
    <!--</section>-->
    <section class="micropost_form">
      <%= render 'shared/micropost_form' %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3>Micropost Feed</h3>
    <%= render 'shared/feed' %>
  </div>
</div>