config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'users/json' => 'users#list_json'
  root 'static_pages#home'
  get 'signup' => 'users#new'
  get 'creategroup' => 'groups#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout'                 => 'sessions#destroy'
  get 'friends/add/:id'          => 'friends#add'
  post 'friends/remove/:id'       => 'friends#remove'
  get 'users/friends/add/:id'    => 'friends#add'
  post 'users/friends/remove/:id' => 'friends#remove'
  get 'friends' => 'friends#index'
  get 'groups/:id' => 'groups#show'
  delete 'groups/remove/:id' => 'groups#destroy'
  post 'users/destroy/:id' => 'users#destroy'
  get 'groups/changestatus/:id' => 'groups#changestatus'
  get 'microposts/destroy/:id' => 'microposts#destroy'
  post 'microposts/post' => 'microposts#post'
  delete 'groups/microposts/destroy/:id' => 'microposts#destroy'
  get 'groups/microposts/edit/:id' => 'microposts#edit'
  get 'microposts/edit/:id' => 'microposts#edit'
  get 'msg/list' => 'text_chat#list', as: :messages
  get 'users/msg/new/:id' => 'text_chat#new', as: :compose
  post 'msg/send' => 'text_chat#send_msg'
  get 'users/video/:id' => 'video_chat#start'
  get 'msg/dialog/:id' => 'text_chat#dialog', as: :dialog
  match 'users/video/auth' => 'video_chat#auth', via: [:get, :post], as: :video
  resources :users
  resources :friends
  resources :groups
  resources :microposts, only: [:create]
end

app/models/friend.rb
class Friend < ActiveRecord::Base
  belongs_to :user
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :microposts, dependent: :destroy
  has_many :users

  def feed
    Micropost.where("group_id = ?", id)
  end

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
end

app/models/user.rb
class User < ActiveRecord::Base
  def feed
    Micropost.where("user_id = ?", id)
  end
  belongs_to :group
  has_many :microposts, dependent: :destroy
  has_many :friends, dependent: :destroy
  has_many :messages, dependent: :destroy
  validates :login, presence: true, length: {maximum: 50},
            uniqueness: {case_sensitive: false}
  has_secure_password

  validates :password, length: {minimum: 5}
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update]
  before_action :correct_user, only: [:edit, :update]
  def new
    @user = User.new
  end
  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])
  end
  def create
    params.permit!
    @user = User.new(params[:user])
    if @user.save
      puts @user
      log_in @user
      flash[:success] = "Welcome to the Social network app"
      redirect_to root_path
    else
      render 'new'
    end
  end
  def destroy
    @user = User.find(params[:id])

    Micropost.destroy_all(user_id:@user.id)
    User.delete(@user)
    flash[:success] = "User has been deleted"
    redirect_to root_path
  end
  def index
    @users = User.all
  end
  def list_json
    render json: User.all
  end
  def edit
    @user = User.find(params[:id])
  end
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end
# Confirms the correct user.
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless @user == current_user
  end
  def user_params
    params.require(:user).permit(:login, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  #Returns the full title on a per-page basis
  def full_title(page_title = '')
    base_title = "Social network"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
  def getstatus(group)
    if group.status == true
      'open'
    else
      'closed'
    end
  end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def admin?
    @current_user.admin
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  def current_user?(user)
    user == current_user
  end
end

app/helpers/text_chat_helper.rb
module TextChatHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <%= f.label :login %>
        <%= f.text_field :login, class: 'form-control' %>
        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>
        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
        <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>
<ul class="users">
  <table class="table">
    <thead>
    <tr>
      <th>Login</th>
      <th></th>
    </tr>
    </thead>
    <tbody>

    <% Array(@users).each do |user| %>
        <% if user.id != current_user.id %>
            <tr>
              <td>
                <%= link_to "#{user.login}", user %>
              </td>
          <% if current_user.admin? %>
                  <td>
                    <%= link_to "Delete user", "users/destroy/#{user.id}", method: :post, class: "btn btn-primary", data: {confirm: "You sure?"} %>
                  </td>
          <% end %>
              <td>
                <% if logged_in? && Friend.find_by(user_id: current_user.id, friend_id: user.id) == nil %>
                    <%= link_to "Add friend", "friends/add/#{user.id}", class: "btn btn-primary" %>
                <% else %>
                    <%= link_to "Remove friend", "friends/remove/#{user.id}", class: "btn btn-primary" %>
                <% end %>
              </td>
            </tr>
        <% end %>
    <% end %>

    <tbody>
    </table>
</ul>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <%= f.label :login %>
        <%= f.text_field :login, class: 'form-control' %>
        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>
        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
        <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.login) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= @user.login %>
      </h1>
      <%= image_tag("peter.jpg", :alt => "user") %>
    </section>
    <section class="communicate">
      <%= link_to "Message", compose_path(@user.id), class: "btn btn-lg btn-primary"%>
    </section>
  </aside>
  <div class="col-md-8">
    <% if @user.microposts.any? %>
        <h3>Microposts (<%= @user.microposts.count %>)</h3>
        <ol class="microposts">
          <%= render @microposts %>
        </ol>
        <%= will_paginate @microposts %>
    <% end %>
  </div>
</div>