config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'users/json' => 'users#list_json'
  root 'static_pages#home'
  get 'signup' => 'users#new'
  get 'creategroup' => 'groups#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout'                 => 'sessions#destroy'
  get 'friends/add/:id'          => 'friends#add'
  post 'friends/remove/:id'       => 'friends#remove'
  get 'users/friends/add/:id'    => 'friends#add'
  post 'users/friends/remove/:id' => 'friends#remove'
  get 'friends' => 'friends#index'
  get 'groups/:id' => 'groups#show'
  delete 'groups/remove/:id' => 'groups#destroy'
  post 'users/destroy/:id' => 'users#destroy'
  get 'groups/changestatus/:id' => 'groups#changestatus'
  get 'microposts/destroy/:id' => 'microposts#destroy'
  post 'microposts/post' => 'microposts#post'
  delete 'groups/microposts/destroy/:id' => 'microposts#destroy'
  get 'groups/microposts/edit/:id' => 'microposts#edit'
  get 'microposts/edit/:id' => 'microposts#edit'
  get 'msg/list' => 'text_chat#list', as: :messages
  get 'users/msg/new/:id' => 'text_chat#new', as: :compose
  post 'msg/send' => 'text_chat#send_msg'
  get 'users/video/:id' => 'video_chat#start'
  get 'msg/dialog/:id' => 'text_chat#dialog', as: :dialog
  match 'users/video/auth' => 'video_chat#auth', via: [:get, :post], as: :video
  resources :users
  resources :friends
  resources :groups
  resources :microposts, only: [:create]
end

app/models/friend.rb
class Friend < ActiveRecord::Base
  belongs_to :user
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :microposts, dependent: :destroy
  has_many :users

  def feed
    Micropost.where("group_id = ?", id)
  end

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
end

app/models/user.rb
class User < ActiveRecord::Base
  def feed
    Micropost.where("user_id = ?", id)
  end
  belongs_to :group
  has_many :microposts, dependent: :destroy
  has_many :friends, dependent: :destroy
  has_many :messages, dependent: :destroy
  validates :login, presence: true, length: {maximum: 50},
            uniqueness: {case_sensitive: false}
  has_secure_password

  validates :password, length: {minimum: 5}
end

app/controllers/text_chat_controller.rb
class TextChatController < ApplicationController
  def list
    @messages = Message.all
    @msg = []
    @messages.each do |m|
      if m.receiver_id == current_user.id
        @msg.append([User.find(m.sender_id), m.text, m.created_at])
      end
    end
    @msg.reverse!
    render :list
  end

  def dialog
    @msgs = Message.all
    params.permit!
    @second = params[:id].to_i
    @name = User.find(@second)
    @dialogsm = []
    @msgs.each do |m|
      if (m.sender_id == current_user.id && m.receiver_id == @second) || (m.receiver_id == current_user.id && m.sender_id == @second)
        @dialogsm.append([User.find(m.sender_id).login, m.text, m.created_at])
       end
    end
    @dialogsm.reverse!
    render :dialog
  end

  def new
    @receiver_id = params[:id]
    render :new
  end

  def send_msg
    params = msg_params
    @msg = Message.new({sender_id: params[:sender], receiver_id: params[:receiver], text: params[:text]})
    @msg.save
    redirect_to messages_path
  end

  def msg_params
    params.permit(:sender, :receiver, :text)
  end
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
  def getstatus(group)
    if group.status == true
      'open'
    else
      'closed'
    end
  end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def admin?
    @current_user.admin
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  def current_user?(user)
    user == current_user
  end
end

app/helpers/text_chat_helper.rb
module TextChatHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/text_chat/dialog.html.erb
<h1>Dialog with <%= @name.login %></h1>
<div class="row">
  <%= image_tag("peter.jpg", :alt => "user") %>
  <div class="col-md-6 col-md-offset-3">
    <%= form_tag(:action => :send_msg) do %>
        <input type="hidden" name="sender" value="<%= current_user.id %>">
        <input type="hidden" name="receiver" value="<%= @second%>">
        <label>
          Message:
          <textarea name="text"></textarea>
        </label>
        <input type="submit" value="OK" class="btn btn-lg btn-primary"/>
    <% end %>
  </div>
</div>
<ul class="msg-list">
  <% @dialogsm.each do |m| %>
      <li class="msg-item">
        <p class="msg-sender"><%= m[0]%></p>
        <p class="msg-time"><%= m[2] %></p>
        <p class="msg-text"><%= m[1] %></p>
      </li>
  <% end %>
</ul>

app/views/text_chat/list.html.erb
<h1>Messages</h1>
<ul class="msg-list">
  <% @msg.each do |m| %>
      <li class="msg-item">
       <p class="msg-sender"><%= m[0].login %></p>
        <p class="msg-time"><%= m[2] %></p>
        <p class="msg-text"><%= m[1] %></p>
        <p><%= link_to 'More', dialog_path(m[0]) %></p>
      </li>
  <% end %>
</ul>

app/views/text_chat/new.html.erb
<h1>Send message</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_tag(:action => :send_msg) do %>
        <input type="hidden" name="sender" value="<%= current_user.id %>">
        <input type="hidden" name="receiver" value="<%= @receiver_id %>">
        <label>
          Message:
          <textarea name="text"></textarea>
        </label>
        <input type="submit" value="OK" class="btn btn-lg btn-primary"/>
    <% end %>
  </div>
</div>