config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'users/json' => 'users#list_json'
  root 'static_pages#home'
  get 'signup' => 'users#new'
  get 'creategroup' => 'groups#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout'                 => 'sessions#destroy'
  get 'friends/add/:id'          => 'friends#add'
  post 'friends/remove/:id'       => 'friends#remove'
  get 'users/friends/add/:id'    => 'friends#add'
  post 'users/friends/remove/:id' => 'friends#remove'
  get 'friends' => 'friends#index'
  get 'groups/:id' => 'groups#show'
  delete 'groups/remove/:id' => 'groups#destroy'
  post 'users/destroy/:id' => 'users#destroy'
  get 'groups/changestatus/:id' => 'groups#changestatus'
  get 'microposts/destroy/:id' => 'microposts#destroy'
  post 'microposts/post' => 'microposts#post'
  delete 'groups/microposts/destroy/:id' => 'microposts#destroy'
  get 'groups/microposts/edit/:id' => 'microposts#edit'
  get 'microposts/edit/:id' => 'microposts#edit'
  get 'msg/list' => 'text_chat#list', as: :messages
  get 'users/msg/new/:id' => 'text_chat#new', as: :compose
  post 'msg/send' => 'text_chat#send_msg'
  get 'users/video/:id' => 'video_chat#start'
  get 'msg/dialog/:id' => 'text_chat#dialog', as: :dialog
  match 'users/video/auth' => 'video_chat#auth', via: [:get, :post], as: :video
  resources :users
  resources :friends
  resources :groups
  resources :microposts, only: [:create]
end

app/models/friend.rb
class Friend < ActiveRecord::Base
  belongs_to :user
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :microposts, dependent: :destroy
  has_many :users

  def feed
    Micropost.where("group_id = ?", id)
  end

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
end

app/models/user.rb
class User < ActiveRecord::Base
  def feed
    Micropost.where("user_id = ?", id)
  end
  belongs_to :group
  has_many :microposts, dependent: :destroy
  has_many :friends, dependent: :destroy
  has_many :messages, dependent: :destroy
  validates :login, presence: true, length: {maximum: 50},
            uniqueness: {case_sensitive: false}
  has_secure_password

  validates :password, length: {minimum: 5}
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
  def getstatus(group)
    if group.status == true
      'open'
    else
      'closed'
    end
  end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def admin?
    @current_user.admin
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  def current_user?(user)
    user == current_user
  end
end

app/helpers/text_chat_helper.rb
module TextChatHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to image_tag('pear.jpg'), root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path, class: "navbar-header" %></li>
        <% if logged_in? %>
            <li><%= link_to "Settings", edit_user_path(current_user), class: "navbar-header" %></li>
            <li><%= link_to 'Friends', friends_path, class: "navbar-header" %></li>
            <li><%= link_to 'Groups', groups_path, class: "navbar-header" %></li>
            <li><%= link_to 'Users', users_path, class: "navbar-header" %></li>
            <li><%= link_to 'Messages', messages_path, class: "navbar-header" %></li>
            <li><%= link_to 'Video', video_path(@current_user.id), class: "navbar-header" %></li>
            <li><%= link_to "Log out", logout_path, method: "delete", class: "navbar-header" %></li>
        <% else %>
            <li><%= link_to "Log in", login_path, class: "navbar-header" %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'angular.min', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
<% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>
<%= render 'layouts/header' %>
<div class="container">
  <%= yield %>
  <footer class="footer">
  </footer>
</div>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        The form contains <%= pluralize(object.errors.count, "error") %>.
      </div>
      <ul>
        <% object.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
    <ol class="microposts">
      <%= render @feed_items %>
    </ol>
    <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="field">
      <%= f.text_area :content, placeholder: "Compose new micropost..." %>
    </div>

      <%= f.hidden_field :group_id, value: @group.id%>
    <%= f.submit :Post, class: "btn btn-primary"%>
<% end %>

app/views/shared/_user_info.html.erb
<h1><%= current_user.login %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>